
version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: amina
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: aminadb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://amina:secret@db:5432/aminadb
    ports:
      - "8000:8000"
    restart: always
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  celery_worker:
    build: .
    command: ["celery", "-A", "celery_worker.celery_app", "worker", "--loglevel=info"]
    depends_on:
      - app
      - redis
    environment:
      DATABASE_URL: postgresql://amina:secret@db:5432/aminadb
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0


volumes:
  postgres_data:
